export const MIGRATION_STATEMENTS = [
  `CREATE TABLE IF NOT EXISTS settings (
    id INTEGER PRIMARY KEY,
    base_rate_per_member REAL NOT NULL,
    payment_due_day INTEGER NOT NULL,
    payment_method TEXT NOT NULL,
    bank_name TEXT NOT NULL,
    bank_account_number TEXT NOT NULL,
    bank_account_name TEXT NOT NULL,
    updated_at TEXT NOT NULL
  )`,
  `CREATE TABLE IF NOT EXISTS families (
    family_id TEXT PRIMARY KEY,
    wakil_name TEXT NOT NULL,
    wakil_phone TEXT NOT NULL,
    family_status TEXT NOT NULL CHECK (family_status IN ('Active', 'Suspended', 'Inactive')),
    joined_month TEXT NOT NULL,
    opening_balance REAL NOT NULL DEFAULT 0,
    notes TEXT,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
  )`,
  `CREATE TABLE IF NOT EXISTS users (
    id TEXT PRIMARY KEY,
    email TEXT NOT NULL UNIQUE,
    password_hash TEXT NOT NULL,
    name TEXT NOT NULL,
    role TEXT NOT NULL CHECK (role IN ('admin', 'wakil')),
    family_id TEXT,
    phone TEXT,
    created_at TEXT NOT NULL,
    FOREIGN KEY (family_id) REFERENCES families(family_id) ON DELETE SET NULL
  )`,
  `CREATE TABLE IF NOT EXISTS members (
    member_id TEXT PRIMARY KEY,
    family_id TEXT NOT NULL,
    member_name TEXT NOT NULL,
    member_status TEXT NOT NULL CHECK (member_status IN ('Aktif', 'Tidak Aktif')),
    relationship TEXT NOT NULL,
    ic_number TEXT,
    created_at TEXT NOT NULL,
    FOREIGN KEY (family_id) REFERENCES families(family_id) ON DELETE CASCADE
  )`,
  `CREATE TABLE IF NOT EXISTS receipts (
    receipt_id TEXT PRIMARY KEY,
    family_id TEXT NOT NULL,
    content_type TEXT NOT NULL,
    image_data TEXT NOT NULL,
    created_at TEXT NOT NULL,
    FOREIGN KEY (family_id) REFERENCES families(family_id) ON DELETE CASCADE
  )`,
  `CREATE TABLE IF NOT EXISTS payments (
    payment_id TEXT PRIMARY KEY,
    family_id TEXT NOT NULL,
    payment_date TEXT NOT NULL,
    payment_month_year TEXT NOT NULL,
    amount_paid REAL NOT NULL,
    expected_amount REAL NOT NULL,
    transaction_reference TEXT NOT NULL,
    receipt_image_url TEXT,
    approval_status TEXT NOT NULL CHECK (approval_status IN ('Pending', 'Approved', 'Rejected')),
    rejection_reason TEXT,
    reviewed_by TEXT,
    reviewed_at TEXT,
    submitted_by TEXT,
    created_at TEXT NOT NULL,
    FOREIGN KEY (family_id) REFERENCES families(family_id) ON DELETE CASCADE
  )`,
  `CREATE TABLE IF NOT EXISTS member_requests (
    request_id TEXT PRIMARY KEY,
    family_id TEXT NOT NULL,
    member_name TEXT NOT NULL,
    relationship TEXT NOT NULL,
    ic_number TEXT,
    status TEXT NOT NULL CHECK (status IN ('Pending', 'Approved', 'Rejected')),
    note TEXT,
    created_at TEXT NOT NULL,
    reviewed_at TEXT,
    FOREIGN KEY (family_id) REFERENCES families(family_id) ON DELETE CASCADE
  )`,
  `CREATE TABLE IF NOT EXISTS claims (
    claim_id TEXT PRIMARY KEY,
    family_id TEXT NOT NULL,
    member_id TEXT NOT NULL,
    claim_date TEXT NOT NULL,
    amount REAL NOT NULL,
    notes TEXT,
    created_by TEXT NOT NULL,
    created_at TEXT NOT NULL,
    FOREIGN KEY (family_id) REFERENCES families(family_id) ON DELETE CASCADE,
    FOREIGN KEY (member_id) REFERENCES members(member_id) ON DELETE CASCADE
  )`,
  `CREATE INDEX IF NOT EXISTS idx_members_family ON members(family_id)`,
  `CREATE INDEX IF NOT EXISTS idx_payments_family ON payments(family_id)`,
  `CREATE INDEX IF NOT EXISTS idx_payments_month ON payments(payment_month_year)`,
  `CREATE INDEX IF NOT EXISTS idx_payments_status ON payments(approval_status)`,
  `CREATE INDEX IF NOT EXISTS idx_requests_family ON member_requests(family_id)`,
  `CREATE INDEX IF NOT EXISTS idx_claims_family ON claims(family_id)`,
  `CREATE INDEX IF NOT EXISTS idx_users_family ON users(family_id)`,
  `CREATE TABLE IF NOT EXISTS activity_log (
    id TEXT PRIMARY KEY,
    actor_id TEXT,
    actor_name TEXT NOT NULL,
    action TEXT NOT NULL,
    detail TEXT NOT NULL,
    created_at TEXT NOT NULL
  )`,
  `CREATE INDEX IF NOT EXISTS idx_activity_created ON activity_log(created_at)`,
];
